// Generated by tools/build-map.mjs from world/entities/locations. Do not edit.
// Named places NPC schedules refer to by id: one per location with a map block.

export type Place = {
  id: string;
  name: string;
  description: string;
  entityId?: string;
  spots: { x: number; y: number }[];
};

export const PLACES: Place[] = [];

export const PLACES_BY_ID = new Map(PLACES.map((p) => [p.id, p]));
